# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0439247808c790a23bfe6f94902514fb"
name = "new-store-locator"
handle = "new-store-locator-3"
application_url = "https://de-austria-legitimate-phil.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "store-locator-xyz-123.myshopify.com"
automatically_update_urls_on_dev = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://de-austria-legitimate-phil.trycloudflare.com/auth/callback",
  "https://de-austria-legitimate-phil.trycloudflare.com/auth/shopify/callback",
  "https://de-austria-legitimate-phil.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
